### ISSUE TITLE
ItemsClient POST not working

### ISSUE THREAD

**Issue by jorbor** [alvaromongon/InventorySystem#4]
This works for me:
`curl -v -XPOST http://localhost:40818/api/Items -d '{"label":"l","Expiration":"\/Date(1460653024770)\/","Type":"blah"}' -H "Content-type: application/json"`

However, running `Succesful_Post_Put_Get_Delete_Test` I get:

```
InventorySystem.EndToEndTests.ItemsEndToEndTests.Succesful_Post_Put_Get_Delete_Test threw exception: 

System.InvalidOperationException: Unexpected status code in response. Expected 'OK'. Actual 'BadRequest'. Method: 'POST' RequestUri: 'http://localhost:40818/api/Items/' ReasonPhrase: 'Bad Request
```

Appears service deserializes item as null.

**Comment by alvaromongon** [comment]
umm no sure what to say here. I have cloned the repository into a new folder. Then open the three specifics solutions (WebApiSolution, WebSocketSolution and EndToEndTestsSolution).

I run the WebApiSolution, and then run "Succesful_Post_Put_Get_Delete_Test". And it is green. no problems.

Maybe some issues with a different visual studio o nuget package version?
