### ISSUE TITLE
PUT not working

### ISSUE THREAD

**Issue by jorbor** [alvaromongon/InventorySystem#7]
```
curl -v -XPUT http://localhost:40818/api/items/123 -d '{"label":"l","Expiration":"\/Date(1460653024770)\/","Type":"blah"}' -H "Content-type: application/json"

{"Message":"The requested resource does not support http method 'PUT'."}
```

Leaving the /123 off the route has identical error.

**Comment by alvaromongon** [comment]
what I am getting is just a null value when deserializing. same comment than for the post: 

I think I have a problem with the deserialization of the DateTime. In this case it works for me from the test but not from curl. It should be fixed anyway. Let me take a look tomorrow and fix the issue.
